#pragma once

#include "CoreMinimal.h"
#include "HAL/IConsoleManager.h"
#include "Templates/UniquePtr.h"

class FHCIAbilityKitAgentDemoConsoleCommands
{
public:
	void Startup();
	void Shutdown();

private:
	TUniquePtr<FAutoConsoleCommand> AgentConfirmGateDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentBlastRadiusDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentTransactionDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentSourceControlDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentRbacDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentLodSafetyDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentPlanDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentPlanDemoJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentPlanValidateDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanFailDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanPreflightDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewDemoCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewLocateCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewSelectCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewSelectJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareApplyCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareApplyJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareConfirmCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareConfirmJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareExecuteTicketCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareExecuteTicketJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimExecuteReceiptCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimExecuteReceiptJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimFinalReportCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimFinalReportJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimArchiveBundleCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimArchiveBundleJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimHandoffEnvelopeCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareSimHandoffEnvelopeJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteIntentCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteIntentJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGWriteEnableRequestCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGWriteEnableRequestJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecutePermitTicketCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecutePermitTicketJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteDispatchRequestCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteDispatchRequestJsonCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteDispatchReceiptCommand;
	TUniquePtr<FAutoConsoleCommand> AgentExecutePlanReviewPrepareStageGExecuteDispatchReceiptJsonCommand;
};
