#pragma once

#include "CoreMinimal.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentApplyConfirmRequest.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentApplyRequest.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentExecuteTicket.h"
#include "Agent/Planner/HCIAbilityKitAgentPlan.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentSimulateExecuteArchiveBundle.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentSimulateExecuteFinalReport.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentSimulateExecuteHandoffEnvelope.h"
#include "Agent/Contracts/StageF/HCIAbilityKitAgentSimulateExecuteReceipt.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteArchiveBundle.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteCommitReceipt.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteCommitRequest.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteDispatchReceipt.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteDispatchRequest.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteFinalReport.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecuteIntent.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecutePermitTicket.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGExecutionReadinessReport.h"
#include "Agent/Contracts/StageG/HCIAbilityKitAgentStageGWriteEnableRequest.h"
#include "Agent/Executor/HCIAbilityKitDryRunDiff.h"
#include "Interfaces/IHttpRequest.h"
#include "Templates/Atomic.h"

struct FHCIAbilityKitAgentDemoState
{
	FHCIAbilityKitAgentPlan AgentPlanPreviewState;
	FHCIAbilityKitDryRunDiffReport AgentExecutorReviewDiffPreviewState;
	FHCIAbilityKitAgentApplyRequest AgentApplyRequestPreviewState;
	FHCIAbilityKitAgentApplyConfirmRequest AgentApplyConfirmRequestPreviewState;
	FHCIAbilityKitAgentExecuteTicket AgentExecuteTicketPreviewState;
	FHCIAbilityKitAgentSimulateExecuteReceipt AgentSimulateExecuteReceiptPreviewState;
	FHCIAbilityKitAgentSimulateExecuteFinalReport AgentSimulateExecuteFinalReportPreviewState;
	FHCIAbilityKitAgentSimulateExecuteArchiveBundle AgentSimulateExecuteArchiveBundlePreviewState;
	FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope AgentSimulateExecuteHandoffEnvelopePreviewState;
	FHCIAbilityKitAgentStageGExecuteIntent AgentStageGExecuteIntentPreviewState;
	FHCIAbilityKitAgentStageGWriteEnableRequest AgentStageGWriteEnableRequestPreviewState;
	FHCIAbilityKitAgentStageGExecutePermitTicket AgentStageGExecutePermitTicketPreviewState;
	FHCIAbilityKitAgentStageGExecuteDispatchRequest AgentStageGExecuteDispatchRequestPreviewState;
	FHCIAbilityKitAgentStageGExecuteDispatchReceipt AgentStageGExecuteDispatchReceiptPreviewState;
	FHCIAbilityKitAgentStageGExecuteCommitRequest AgentStageGExecuteCommitRequestPreviewState;
	FHCIAbilityKitAgentStageGExecuteCommitReceipt AgentStageGExecuteCommitReceiptPreviewState;
	FHCIAbilityKitAgentStageGExecuteFinalReport AgentStageGExecuteFinalReportPreviewState;
	FHCIAbilityKitAgentStageGExecuteArchiveBundle AgentStageGExecuteArchiveBundlePreviewState;
	FHCIAbilityKitAgentStageGExecutionReadinessReport AgentStageGExecutionReadinessReportPreviewState;
	TAtomic<bool> bRealLlmPlanCommandInFlight{false};
	TArray<TSharedPtr<IHttpRequest, ESPMode::ThreadSafe>> RealLlmProbeRequests;

	void ResetPreviewStates();
};

FHCIAbilityKitAgentDemoState& HCI_GetAgentDemoState();