#pragma once

#include "CoreMinimal.h"
struct FHCIAbilityKitAgentApplyConfirmRequest;
struct FHCIAbilityKitAgentApplyRequest;
struct FHCIAbilityKitAgentExecuteTicket;
struct FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope;
struct FHCIAbilityKitAgentSimulateExecuteArchiveBundle;
struct FHCIAbilityKitAgentSimulateExecuteFinalReport;
struct FHCIAbilityKitAgentSimulateExecuteReceipt;
struct FHCIAbilityKitAgentStageGExecuteIntent;
struct FHCIAbilityKitAgentStageGWriteEnableRequest;
struct FHCIAbilityKitAgentStageGExecutePermitTicket;
struct FHCIAbilityKitAgentStageGExecuteDispatchRequest;
struct FHCIAbilityKitAgentStageGExecuteDispatchReceipt;
struct FHCIAbilityKitAgentStageGExecuteCommitReceipt;
struct FHCIAbilityKitAgentStageGExecuteFinalReport;
struct FHCIAbilityKitDryRunDiffReport;

class HCIABILITYKITRUNTIME_API FHCIAbilityKitAgentExecutorStageGExecuteFinalReportBridge
{
public:
	static bool BuildStageGExecuteFinalReport(
		const FHCIAbilityKitAgentStageGExecuteCommitReceipt& StageGExecuteCommitReceipt,
		const FString& ExpectedStageGExecuteCommitReceiptId,
		const FString& ExpectedStageGExecuteCommitRequestId,
		const FString& ExpectedStageGExecuteCommitRequestDigest,
		const FHCIAbilityKitAgentStageGExecuteDispatchReceipt& StageGExecuteDispatchReceipt,
		const FHCIAbilityKitAgentStageGExecuteDispatchRequest& StageGExecuteDispatchRequest,
		const FHCIAbilityKitAgentStageGExecutePermitTicket& StageGExecutePermitTicket,
		const FHCIAbilityKitAgentStageGWriteEnableRequest& StageGWriteEnableRequest,
		const FHCIAbilityKitAgentStageGExecuteIntent& StageGExecuteIntent,
		const FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope& SimHandoffEnvelope,
		const FHCIAbilityKitAgentSimulateExecuteArchiveBundle& SimArchiveBundle,
		const FHCIAbilityKitAgentSimulateExecuteFinalReport& SimFinalReport,
		const FHCIAbilityKitAgentSimulateExecuteReceipt& SimExecuteReceipt,
		const FHCIAbilityKitAgentExecuteTicket& CurrentExecuteTicket,
		const FHCIAbilityKitAgentApplyConfirmRequest& CurrentConfirmRequest,
		const FHCIAbilityKitAgentApplyRequest& CurrentApplyRequest,
		const FHCIAbilityKitDryRunDiffReport& CurrentReviewReport,
		FHCIAbilityKitAgentStageGExecuteFinalReport& OutReceipt);
};
