#pragma once

#include "CoreMinimal.h"

struct FHCIAbilityKitAgentApplyConfirmRequest;
struct FHCIAbilityKitAgentApplyRequest;
struct FHCIAbilityKitAgentExecuteTicket;
struct FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope;
struct FHCIAbilityKitAgentSimulateExecuteArchiveBundle;
struct FHCIAbilityKitAgentSimulateExecuteFinalReport;
struct FHCIAbilityKitAgentSimulateExecuteReceipt;
struct FHCIAbilityKitAgentStageGExecuteIntent;
struct FHCIAbilityKitAgentStageGWriteEnableRequest;
struct FHCIAbilityKitAgentStageGExecutePermitTicket;
struct FHCIAbilityKitAgentStageGExecuteDispatchRequest;
struct FHCIAbilityKitAgentStageGExecuteDispatchReceipt;
struct FHCIAbilityKitDryRunDiffReport;

class HCIABILITYKITRUNTIME_API FHCIAbilityKitAgentExecutorStageGExecuteDispatchReceiptBridge
{
public:
	static bool BuildStageGExecuteDispatchReceipt(
		const FHCIAbilityKitAgentStageGExecuteDispatchRequest& StageGExecuteDispatchRequest,
		const FString& ExpectedStageGExecuteDispatchRequestId,
		const FHCIAbilityKitAgentStageGExecutePermitTicket& StageGExecutePermitTicket,
		const FHCIAbilityKitAgentStageGWriteEnableRequest& StageGWriteEnableRequest,
		const FHCIAbilityKitAgentStageGExecuteIntent& StageGExecuteIntent,
		const FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope& SimHandoffEnvelope,
		const FHCIAbilityKitAgentSimulateExecuteArchiveBundle& SimArchiveBundle,
		const FHCIAbilityKitAgentSimulateExecuteFinalReport& SimFinalReport,
		const FHCIAbilityKitAgentSimulateExecuteReceipt& SimExecuteReceipt,
		const FHCIAbilityKitAgentExecuteTicket& CurrentExecuteTicket,
		const FHCIAbilityKitAgentApplyConfirmRequest& CurrentConfirmRequest,
		const FHCIAbilityKitAgentApplyRequest& CurrentApplyRequest,
		const FHCIAbilityKitDryRunDiffReport& CurrentReviewReport,
		FHCIAbilityKitAgentStageGExecuteDispatchReceipt& OutRequest);
};



