#pragma once

#include "CoreMinimal.h"

struct FHCIAbilityKitAgentApplyConfirmRequest;
struct FHCIAbilityKitAgentApplyRequest;
struct FHCIAbilityKitAgentExecuteTicket;
struct FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope;
struct FHCIAbilityKitAgentSimulateExecuteArchiveBundle;
struct FHCIAbilityKitAgentSimulateExecuteFinalReport;
struct FHCIAbilityKitAgentSimulateExecuteReceipt;
struct FHCIAbilityKitAgentStageGExecuteIntent;
struct FHCIAbilityKitAgentStageGWriteEnableRequest;
struct FHCIAbilityKitAgentStageGExecutePermitTicket;
struct FHCIAbilityKitDryRunDiffReport;

class HCIABILITYKITRUNTIME_API FHCIAbilityKitAgentExecutorStageGExecutePermitTicketBridge
{
public:
	static bool BuildStageGExecutePermitTicket(
		const FHCIAbilityKitAgentStageGWriteEnableRequest& StageGWriteEnableRequest,
		const FString& ExpectedStageGWriteEnableRequestId,
		const FHCIAbilityKitAgentStageGExecuteIntent& StageGExecuteIntent,
		const FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope& SimHandoffEnvelope,
		const FHCIAbilityKitAgentSimulateExecuteArchiveBundle& SimArchiveBundle,
		const FHCIAbilityKitAgentSimulateExecuteFinalReport& SimFinalReport,
		const FHCIAbilityKitAgentSimulateExecuteReceipt& SimExecuteReceipt,
		const FHCIAbilityKitAgentExecuteTicket& CurrentExecuteTicket,
		const FHCIAbilityKitAgentApplyConfirmRequest& CurrentConfirmRequest,
		const FHCIAbilityKitAgentApplyRequest& CurrentApplyRequest,
		const FHCIAbilityKitDryRunDiffReport& CurrentReviewReport,
		FHCIAbilityKitAgentStageGExecutePermitTicket& OutRequest);
};


