#pragma once

#include "CoreMinimal.h"

struct FHCIAbilityKitAgentApplyConfirmRequest;
struct FHCIAbilityKitAgentApplyRequest;
struct FHCIAbilityKitAgentExecuteTicket;
struct FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope;
struct FHCIAbilityKitAgentSimulateExecuteArchiveBundle;
struct FHCIAbilityKitAgentSimulateExecuteFinalReport;
struct FHCIAbilityKitAgentSimulateExecuteReceipt;
struct FHCIAbilityKitAgentStageGExecuteIntent;
struct FHCIAbilityKitAgentStageGWriteEnableRequest;
struct FHCIAbilityKitAgentStageGExecutePermitTicket;
struct FHCIAbilityKitAgentStageGExecuteDispatchRequest;
struct FHCIAbilityKitDryRunDiffReport;

class HCIABILITYKITRUNTIME_API FHCIAbilityKitAgentExecutorStageGExecuteDispatchRequestBridge
{
public:
	static bool BuildStageGExecuteDispatchRequest(
		const FHCIAbilityKitAgentStageGExecutePermitTicket& StageGExecutePermitTicket,
		const FString& ExpectedStageGExecutePermitTicketId,
		const FHCIAbilityKitAgentStageGWriteEnableRequest& StageGWriteEnableRequest,
		const FHCIAbilityKitAgentStageGExecuteIntent& StageGExecuteIntent,
		const FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope& SimHandoffEnvelope,
		const FHCIAbilityKitAgentSimulateExecuteArchiveBundle& SimArchiveBundle,
		const FHCIAbilityKitAgentSimulateExecuteFinalReport& SimFinalReport,
		const FHCIAbilityKitAgentSimulateExecuteReceipt& SimExecuteReceipt,
		const FHCIAbilityKitAgentExecuteTicket& CurrentExecuteTicket,
		const FHCIAbilityKitAgentApplyConfirmRequest& CurrentConfirmRequest,
		const FHCIAbilityKitAgentApplyRequest& CurrentApplyRequest,
		const FHCIAbilityKitDryRunDiffReport& CurrentReviewReport,
		bool bExecuteDispatchConfirmed,
		FHCIAbilityKitAgentStageGExecuteDispatchRequest& OutRequest);
};


