#pragma once

#include "CoreMinimal.h"

struct FHCIAbilityKitAgentApplyConfirmRequest;
struct FHCIAbilityKitAgentApplyRequest;
struct FHCIAbilityKitAgentExecuteTicket;
struct FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope;
struct FHCIAbilityKitAgentSimulateExecuteArchiveBundle;
struct FHCIAbilityKitAgentSimulateExecuteFinalReport;
struct FHCIAbilityKitAgentSimulateExecuteReceipt;
struct FHCIAbilityKitAgentStageGExecuteIntent;
struct FHCIAbilityKitAgentStageGWriteEnableRequest;
struct FHCIAbilityKitDryRunDiffReport;

class HCIABILITYKITRUNTIME_API FHCIAbilityKitAgentExecutorStageGWriteEnableRequestBridge
{
public:
	static bool BuildStageGWriteEnableRequest(
		const FHCIAbilityKitAgentStageGExecuteIntent& StageGExecuteIntent,
		const FString& ExpectedStageGExecuteIntentId,
		const FHCIAbilityKitAgentSimulateExecuteHandoffEnvelope& SimHandoffEnvelope,
		const FHCIAbilityKitAgentSimulateExecuteArchiveBundle& SimArchiveBundle,
		const FHCIAbilityKitAgentSimulateExecuteFinalReport& SimFinalReport,
		const FHCIAbilityKitAgentSimulateExecuteReceipt& SimExecuteReceipt,
		const FHCIAbilityKitAgentExecuteTicket& CurrentExecuteTicket,
		const FHCIAbilityKitAgentApplyConfirmRequest& CurrentConfirmRequest,
		const FHCIAbilityKitAgentApplyRequest& CurrentApplyRequest,
		const FHCIAbilityKitDryRunDiffReport& CurrentReviewReport,
		bool bWriteEnableConfirmed,
		FHCIAbilityKitAgentStageGWriteEnableRequest& OutRequest);
};


